### ISSUE TITLE
Releasing?

### ISSUE THREAD

**Issue by Volgeop** [Skizzles/Tinkers#1]
Hi, could you please release new ver?

**Comment by Skizzles** [comment]
Hello,

We are currently working on reworking the plugin and adding 1.16 support among other cleanup. A release will be posted when it is done. The add-on is listed as WIP on the add-on page.

Thanks.

**Comment by Volgeop** [comment]
How it looks please?

**Comment by Volgeop** [comment]
One month ago, something new @Skizzles ? Players are waiting for it.

**Comment by Skizzles** [comment]
@Volgeop Can you not rush us lol? This is a lot of work. Unless you care to assist with recoding it then do not rush us.
